#!/usr/bin/perl -w

use strict;
use NethServer::BackupConfig;
use esmith::ConfigDB;
use vars qw();

sub rotate_backup_files{

	# define the backup folder
	my $bkp_dir = NethServer::BackupConfig::DESTINATION_DIR;

	#open the backups folder for processing
	opendir (DIR, $bkp_dir) or die "Error opening '$bkp_dir': '$!'\n";
	
	my @bkp_files = grep /^backup-config_.*\.tar\.xz$/, readdir (DIR);
	
	#check that the filename array contains something (at least 1 file found)
	if (! @bkp_files) {
						# if it does not contain a filename; exit 
						exit 0;
						
						} else {
								# if we have something in the bkp_files array we do a sort so we will get the newest files first
								my @bkp_files_sorted= reverse sort @bkp_files; 
								
								# we check that the array contains more than 15 elements
								if (@bkp_files_sorted > 15 ){
															 # if it is greater than 15 then put extra elements in a separate array
															 my @slice = @bkp_files_sorted[14 .. $#bkp_files_sorted];
															 
															 # then delete elements from the array 15+
															 foreach my $file_extra (@slice) {
									
															 # remove the backup file and the md5 files
															 if ( ! -f NethServer::BackupConfig::DESTINATION_DIR.$file_extra ) {
																																print $file_extra." configuration backup file not found! \n";
																																} else {
																																		unlink "/var/lib/nethserver/backup/".$file_extra or warn "Error removing ".$file_extra;
																																		unlink "/var/lib/nethserver/backup/".$file_extra.".md5" or warn "Error removing ".$file_extra.".md5";
																																		unlink "/var/lib/nethserver/backup/".$file_extra."-content.md5" or warn "Error removing ".$file_extra."-content.md5";
																																		};
																		
																													};
																} else {
																		# the array contains under 15 elements so no rotation needed; exit
																		exit 0;
																		};	# end else if more than 15 files found in array
								
								
								
								
								
								}; # end else if no files found in dir.

}


rotate_backup_files();

exit(0);
