#! /usr/bin/perl -w
#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::ConfigDB;
use NethServer::BackupConfig;
use POSIX qw/strftime/;

my $conf = esmith::ConfigDB->open || die("Could not open config db\n");
my $backup = $conf->get('backup-config');
my $status = $backup->prop('status') || 'disabled';
# valid values for notify are: always, error, never
my $notify = $backup->prop('notify') || 'error';
my $notify_to = $backup->prop('notifyTo') || 'admin@localhost';

exit 0 unless ($status eq 'enabled');

$backup = new NethServer::BackupConfig($notify,$notify_to);

$backup->cleanup_notification();
$backup->notify("===== Report for configuration backup =====\n");

my $start = time;
$backup->logger("START","Backup config started");
$backup->notify("Backup started at %s", strftime('%F %T',localtime));

if ($status = system(qw(/sbin/e-smith/signal-event pre-backup-config)))
{
    $backup->notify("Pre backup scripts status: ERROR");
    $backup->bad_exit("Event pre-backup-config failed", $status>>8);
}
$backup->logger("STEP","pre-backup-config done");
$backup->notify("Pre backup scripts status: SUCCESS");

if ($status = system("/etc/e-smith/events/actions/backup-config-execute"))
{
    $backup->notify("Backup script status: ERROR");
    $backup->bad_exit("Action backup-config-execute failed", $status>>8);
}
$backup->logger("STEP","backup-config-execute done");
$backup->notify("Backup script status: SUCCESS");

if ($status = system(qw(/sbin/e-smith/signal-event post-backup-config)))
{
    $backup->notify("Post backup scripts status: ERROR");
    $backup->bad_exit("Event post-backup-config failed", $status>>8);
}
$backup->notify("Post backup scripts status: SUCCESS");

$backup->logger("SUCCESS","Backup config done");
$backup->notify("Backup status: SUCCESS");
$backup->notify("Backup ended at %s", strftime('%F %T',localtime));
my $duration = time - $start;
$backup->notify("Time elapsed: %s hours, %s minutes, %s seconds", ($duration/(60*60))%24, ($duration/60)%60, $duration%60);

$backup->send_notification();

exit 0;
