#! /usr/bin/perl -w
#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

###
# must be added to sudo
###

use strict;
use NethServer::BackupConfig;

my $bkp_file=$ARGV[0];

my $status;

my $backup = new NethServer::BackupConfig();

# my $tracker = NethServer::TrackerClient->new();

if (not defined $bkp_file) { print "No backup file specified"; die; };

if ( ! -f NethServer::BackupConfig::DESTINATION_DIR.$bkp_file ) {

        print "Backup file not found or can't delete backup ".$bkp_file;
        die;
        
    } else {
		unlink "/var/lib/nethserver/backup/".$bkp_file or warn "Error removing ".$bkp_file;
		unlink "/var/lib/nethserver/backup/".$bkp_file.".md5" or warn "Error removing ".$bkp_file.".md5";
		unlink "/var/lib/nethserver/backup/".$bkp_file."-content.md5" or warn "Error removing ".$bkp_file."-content.md5";
		
		};


exit 0;
