#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);


#--------------------------------------------------
# actions for nethserver-backup-config-update event
#--------------------------------------------------

my $event = "nethserver-backup-config-update";

event_actions($event, 'initialize-default-databases' => '00');

#--------------------------------------------------
# actions for nethserver-backup-config-save event
#--------------------------------------------------

$event = "nethserver-backup-config-save";


#--------------------------------------------------
# actions for post-restore-config event
#--------------------------------------------------

$event = "post-restore-config";

event_actions($event, qw(
    nethserver-backup-config-setupgradeflag 00
    adjust-fixnetwork-flag 01
    interface-update-cond 70
    system-adjust 70
));

#--------------------------------------------------
# actions for post-restore-data event
#--------------------------------------------------

$event = "post-restore-data";

event_actions($event, qw(
    nethserver-backup-config-clearupgradeflag 99
));

#--------------------------------------------------
# actions for pre-backup-config event
#--------------------------------------------------

$event = "pre-backup-config";

event_actions($event,
    'nethserver-backup-config-list-packages' => '50',
);

validator_actions('config-backup-upload', qw(
    valid-nsconfbackup 20
));
