#! /usr/bin/perl -w
#
# Copyright (C) 2013 Nethesis S.r.l.
# Copyright (C) 2006 SME Server
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
require File::Temp;
use esmith::ConfigDB;
use esmith::Backup;

$ENV{PATH} = "/sbin/e-smith:/sbin:/bin:/usr/bin";

my $backup = new esmith::Backup('config');

$backup->logger("START","Starting backup");

if ( -e esmith::Backup::BACKUP_CONFIG_DESTINATION ) {
    unlink(esmith::Backup::BACKUP_CONFIG_DESTINATION);
}

# Read include and exclude from config directory
my @include_files = $backup->includes(esmith::Backup::BACKUP_CONFIG_CONF_DIR);
#print "include="; print join(' ',@include_files); print "\n";
if (!@include_files) {
    $backup->bad_exit("Nothing to backup",1);
}
my @exclude_files = $backup->excludes(esmith::Backup::BACKUP_CONFIG_CONF_DIR);
#print "exclude="; print join(' ',@exclude_files); print "\n";

if ($backup->changed(\@include_files, \@exclude_files)) {
   $backup->backup_config(\@include_files, \@exclude_files);
   $backup->logger("SUCCESS","Backup done - 0");
} else {
   $backup->logger("SUCCESS","No backup needed - 0");
}


exit 0;

