#!/bin/bash

archive=$1
content_md5="$archive-content.md5"
archive_md5=$archive".md5"

rm -f $content_md5 $archive_md5

if [ ! -f $archive ]; then
   exit 1
fi

for i in `/bin/tar -tJf $archive`;  do
    if [ -f /$i ]; then 
        /usr/bin/md5sum /$i >> $content_md5 
    fi
done

/usr/bin/md5sum $archive > $archive_md5

exit(0);
