#!/usr/bin/perl -w

use strict;
use NethServer::BackupConfig;
use esmith::ConfigDB;
use JSON;

my %backup=get_backup_files();

sub get_backup_files{

	# define the backup folder
	my $bkp_dir = NethServer::BackupConfig::DESTINATION_DIR;

	#open the backups folder for processing
	opendir my $dh, $bkp_dir or die "Error opening '$bkp_dir': '$!'\n";
	
	my @bkp_files = grep /^backup-config_.*\.tar\.xz$/, readdir $dh;
	
	#check that the filename array contains something (at least 1 file found)
	if (! @bkp_files) {
						
						# if it does not contain a filename; return nothing
						return;
						
						} else {
								
								# if we have something in the bkp_files array we do a sort
								my @bkp_files_sorted= reverse sort @bkp_files; 
								
								foreach $file_info (@bkp_files_sorted) {
									my @stats = stat(NethServer::BackupConfig::DESTINATION_DIR.$file_info);
									$backup{'path'} = NethServer::BackupConfig::DESTINATION_DIR.$file_info; 
									$backup{'name'} = $file_info; 
									$backup{'date'} = $stats[9]; 
									$backup{'size'} = $stats[7]; 
									};
								
								# and we return the file with the latest date in filename
								return $backup;
								};
}





#if ( -f NethServer::BackupConfig::DESTINATION ) {
#    my @stats = stat(NethServer::BackupConfig::DESTINATION);
#    $backup{'name'} = NethServer::BackupConfig::DESTINATION; 
#    $backup{'date'} = $stats[9]; 
#    $backup{'size'} = $stats[7]; 
#}



print to_json(\%backup);

exit(0);
