#!/bin/bash

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Check if the configuration backup to restore has a subscription.
# Accept one parameter: the name of the backup file
#

# Read the backup file name as first paramater
# If empty, fallback to default location: /var/lib/nethserver/backup/backup-config.tar.xz
if [ -z "$1" ]; then
    backup=/var/lib/nethserver/backup/backup-config.tar.xz
else
    backup=$1
fi

# Backup not found
if [ ! -f "$backup" ]; then
    exit 2
fi

configdb=/var/lib/nethserver/db/configuration
tmpdir=$(mktemp -d /tmp/restore-yumrepos.XXXXXXX)
tmpdb=$(mktemp -u /var/lib/nethserver/db/configuration.XXXXXXXX)
trap "rm -rf ${tmpdir}" EXIT

tar -x -C "${tmpdir}" -f $backup var/lib/nethserver/db/configuration

systemId=$(/sbin/e-smith/config getprop subscription SystemId)
systemId_backup=$(/sbin/e-smith/db ${tmpdir}/var/lib/nethserver/db/configuration getprop subscription SystemId)

# Restoring a community backup, no registration required
if [[ -z ${systemId_backup} ]]; then
    exit 0
fi

# Registration is required
if [[ -z ${systemId} && ! -z ${systemId_backup} ]]; then
    exit 1
fi

exit 0
