#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Knowing the execution context could be useful to pre/post backup-config 
# event actions:
export BACKUP_CONFIG_CRONJOB=1

BackupDataStatus=$(/sbin/e-smith/config getprop backup-data status)
if [[ "${BackupDataStatus}" == "enabled" ]]; then
    exit 0;
fi

# Run the backup configuration
/sbin/e-smith/backup-config > /dev/null

if [[ $? == 0 ]]; then
    /etc/e-smith/events/actions/nethserver-backup-config-push2history 
fi
