#!/usr/bin/perl

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use warnings;
use strict;
use esmith::NetworksDB;
use esmith::ConfigDB;

my $ndb = esmith::NetworksDB->open();
my $cdb = esmith::ConfigDB->open();

if (grep(/^--skip-network$/, @ARGV)) {

    # Delete all network interfaces
    foreach my $item ($ndb->get_all()) {
        if ($item->prop('type') =~ m/^(ethernet|bridge|bond|slave|vlan|alias)$/) {
            $item->delete();
        }
        if ($item->key eq 'ppp0') {
            $item->set_prop('type', 'xdsl-disabled');
        }
    }

    # Preserve upstream DNS, which will be overridden by the below action
    my $dns = $cdb->get_prop('dns', 'NameServers');
    system("/etc/e-smith/events/actions/nethserver-base-initialize-db");
    # Restore previously saved DNS
    $cdb->set_prop('dns', 'NameServers', $dns);
}
