#!/usr/bin/python

#
# Copyright (C) 2017 Nethesis S.r.l.
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import sys
import re
import subprocess
import os.path

exit_code = None

try:
    packages = []
    if not os.path.isfile('/var/lib/nethserver/backup/package-list'):
        sys.exit(0)

    with open('/var/lib/nethserver/backup/package-list') as fp:
        for line in fp:
            packages.append(line.rstrip())

    args = ['/usr/bin/rpm', '-q', '--whatprovides']
    args.extend(packages)
    exit_code = subprocess.check_call(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
except subprocess.CalledProcessError as e:
    exit_code = e.returncode

if(exit_code > 0):
    open('/var/run/.nethserver-reinstall-packages', 'a').close()
