#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

EXIT_NOTHING_TODO=0
EXIT_ERROR=1
EXIT_POST_RESTORE=2
EXIT_MUST_RESTORE=3
EXIT_NEED_INPUT=4

# Check what is the next step
/usr/libexec/nethserver/upgrade-next-step
next_step=$?

if [ $next_step == $EXIT_POST_RESTORE ]; then
    /sbin/e-smith/signal-event post-restore-data
elif [ $next_step == $EXIT_ERROR ]; then
    echo "[WARNING]: backup-data status is invalid!"
fi

