#!/bin/bash

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

while (( $# > 0 )); do
    if [[ $1 == '--no-reinstall' ]]; then
        no_reinstall=1
    fi
    shift
done

if [[ -n ${no_reinstall} ]]; then
    exit 0
fi

packagelist_path=/var/lib/nethserver/backup/package-list
backup_path=/var/lib/nethserver/backup/backup-config.tar.xz

packages=($(tar -x -O -f ${backup_path} ${packagelist_path:1} | sed -f /etc/nethserver/ns6upgrade-package-list.sed))

if (( ${#packages[@]} == 0 )); then
    echo "[WARNING] no packages listed for download"
    exit 0
fi

yum -y --downloadonly install "${packages[@]}"
