#!/bin/bash
#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

packagelist_path=/var/lib/nethserver/backup/package-list

if [ ! -f ${packagelist_path} ]; then
    echo "[WARNING] restore-config-reinstall: package-list not found, skipped"
    exit 0
fi

# Migrate packages from NS 6 to NS 7
# See: http://docs.nethserver.org/en/v7/release_notes.html#discontinued-packages
sed -i -f /etc/nethserver/ns6upgrade-package-list.sed ${packagelist_path}

packages=$(sed ':a;N;$!ba;s/\n/ /g' ${packagelist_path});
yum --disableplugin=nethserver_events install -y $packages
