#!/bin/bash
#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#


if [ -f /var/lib/nethserver/backup/package-list ]; then

    # Migrate packages from NS 6 to NS 7
    # See: http://docs.nethserver.org/en/v7/release_notes.html#discontinued-packages
    sed -i \
       -e 's/^nethserver-vpn$/nethserver-openvpn\nnethserver-ipsec-tunnels/'  \
       -e 's/^nethserver-collectd-web$/nethserver-cgp/' \
       -e 's/^nethserver-fetchmail$/nethserver-getmail/' \
       -e 's/^nethserver-snort$/nethserver-suricata/' \
       -e 's/^nethserver-ibays$/nethserver-virtualhosts\nnethserver-samba/' \
       -e '/^nethserver-c-icap$/d' \
    /var/lib/nethserver/backup/package-list

    packages=$(sed ':a;N;$!ba;s/\n/ /g' /var/lib/nethserver/backup/package-list);
    yum --disableplugin=nethserver_events install -y $packages
fi
