#!/bin/bash

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Check yum manpage for exit codes meaning

yum -y --setopt=exit_on_lock=1 check-update nethserver-\* >/dev/null </dev/null
exit_code=$?
if [[ ${exit_code} == 100 ]]; then
    echo "[ERROR] the system is not up-to-date. Install all updates before running restore-config!"
    exit 100
fi

exit ${exit_code}