#!/usr/bin/python

#
# Copyright (C) 2015 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import gettext
import json
import sys
import re
import subprocess
import os.path

exit_code = None

try:
    args = ['/usr/libexec/nethserver/upgrade-next-step']
    exit_code = subprocess.check_call(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
except subprocess.CalledProcessError as e:
    exit_code = e.returncode

if(exit_code == 3):
    gettext.textdomain('nethserver-backup-config')
    msg = {
        "action": {
            "label": gettext.gettext('Do not reboot the system! Run the "restore-data" procedure'),
        },
        "text": gettext.gettext('Complete the restore procedure by running the "restore-data" command from a root shell'),
        "icon": "hand-paper-o"
    }
    json.dump(msg, sys.stdout)
elif(exit_code == 4):
    gettext.textdomain('nethserver-backup-config')
    msg = {
        "action": {
            "label": gettext.gettext('Do not reboot the system! Restore procedure is incomplete'),
            "url": "/BackupData"
        },
        "text": gettext.gettext('Either enable backup and run "restore-data" or complete the restore procedure by running the "signal-event post-restore-data" command from a root shell'),
        "icon": "hand-paper-o"
    }
    json.dump(msg, sys.stdout)



